---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
  labels:
    app.kubernetes.io/name: site
    app.kubernetes.io/version: ${RELEASE}
    app.kubernetes.io/component: http
    app.kubernetes.io/part-of: site
spec:
  tls:
    - hosts:
        - kunkels.me
        - www.kunkels.me
      secretName: tls-kunkels-me
  rules:
    - host: kunkels.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: site
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: site
  labels:
    app.kubernetes.io/name: site
    app.kubernetes.io/version: ${RELEASE}
    app.kubernetes.io/component: http
    app.kubernetes.io/part-of: site
spec:
  selector:
    app.kubernetes.io/name: site
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  labels:
    app.kubernetes.io/name: site
    app.kubernetes.io/version: ${RELEASE}
    app.kubernetes.io/component: http
    app.kubernetes.io/part-of: site
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: site
  template:
    metadata:
      labels:
        app.kubernetes.io/name: site
        app.kubernetes.io/version: ${RELEASE}
        app.kubernetes.io/component: http
        app.kubernetes.io/part-of: site
    spec:
      imagePullSecrets:
        - name: ghcr.io
      containers:
        - name: app
          image: ghcr.io/chiel/kunkels.me:${RELEASE}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
