---
apiVersion: v1
kind: Namespace
metadata:
  name: kunkels

---
apiVersion: v1
kind: Service
metadata:
  namespace: kunkels
  name: caddy
spec:
  type: LoadBalancer
  selector:
    app: caddy
  ports:
  - name: http
    port: 80
  - name: https
    port: 443

---
apiVersion: v1
kind: Service
metadata:
  namespace: kunkels
  name: site
spec:
  selector:
    app: site
  ports:
  - name: http
    port: 80
    targetPort: 14728

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kunkels
  name: caddy-config
data:
  Caddyfile: |
    dev.kunkels.me {
      tls chiel@kunkels.me
      gzip
      header / -Server
      proxy / site
    }

    chielkunkels.com {
      tls chiel@kunkels.me
      header / -Server
      redir https://kunkels.me
    }

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kunkels
  name: caddy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: joshix/caddy
        env:
        - name: CADDYPATH
          value: /data/.caddy
        volumeMounts:
        - name: caddy-config
          mountPath: /var/www/html
        - name: kunkels-data
          mountPath: /data
      volumes:
      - name: caddy-config
        configMap:
          name: caddy-config
      - name: kunkels-data
        gcePersistentDisk:
          pdName: kunkels-data
          fsType: ext4

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kunkels
  name: site
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: app
        image: gcr.io/kunkels-core/kunkels-site:$SHORT_SHA
        env:
        - name: NODE_ENV
          value: production
