---
apiVersion: v1
kind: Namespace
metadata:
  name: kunkels

---
apiVersion: v1
kind: Service
metadata:
  namespace: kunkels
  name: site
spec:
  selector:
    app: site
  ports:
  - name: http
    port: 80
    targetPort: 14728

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kunkels
  name: site
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: app
        image: gcr.io/kunkels-core/kunkels-site:$SHORT_SHA
        env:
        - name: NODE_ENV
          value: production
