images:
- gcr.io/$PROJECT_ID/kunkels-site:$SHORT_SHA

steps:
- name: gcr.io/cloud-builders/yarn
  args: ['install']

- name: gcr.io/cloud-builders/yarn
  args: ['build']

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kunkels-site:$SHORT_SHA', '.']
