version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: yarn watch:server
    depends_on:
    - build
    volumes:
    - .:/app

  build:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: yarn watch:build
    volumes:
    - .:/app

  caddy:
    image: joshix/caddy
    ports:
    - 14728:80
    volumes:
    - .:/var/www/html
