name: CI

on:
  push:
    branches:

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: node_modules
      - uses: actions/setup-node@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          run_install: true

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    needs:
      - install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
      - name: Lint
        run: pnpm run lint

  build:
    name: Build
    runs-on: ubuntu-24.04
    needs:
      - install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
      - name: Build
        run: pnpm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

  build-docker:
    name: Build docker image
    runs-on: ubuntu-24.04
    needs:
      - build
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/chiel/kunkels.me:${{ github.sha }}
          context: .
